# > google重定向
^https?:\/\/(www\.)?(g|google)\.cn url 302 https://www.google.com
hostname = www.g.cn,www.google.cn
# > 修改浏览器UA
#QX
#^http:// url request-header (\r\n)User-[A|a]gent:.+(\r\n) request-header $1User-Agent: Fuck$2
