hostname = cn.pornhubpremium.com,*.pornhub.com,www.g.cn,www.google.cn
# > PornHub 
^https:\/\/(cn|www)\.pornhub\.com\/_xa\/ads url reject-dict
^https?:/\/(cn|www)\.pornhub\.com\/($|(view|video).*$) url script-response-body https://github.com/ddgksf2013/Scripts/raw/master/pornhub.js
#hostname = *.pornhub.com
# > google重定向
^https?:\/\/(www\.)?(g|google)\.cn url 302 https://www.google.com
#hostname = www.g.cn,www.google.cn
# > 修改浏览器UA
#QX
#^http:// url request-header (\r\n)User-[A|a]gent:.+(\r\n) request-header $1User-Agent: Fuck$2
